# Netlify Configuration File
# Documentation: https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # The command Vite uses to build the production bundle
  command = "npm run build"
  
  # The directory where Vite outputs production files
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://emotion-support-app.onrender.com/api/:splat"
  status = 200
  force = true

# Rule 2: Redirect all other requests to index.html for React SPA Routing (prevents 404 on refresh)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
